AllCops:
  Exclude:
    - db/migrate/*
    - lib/pay/version.rb
    - test/dummy/**/*
    - test/models/subscription_test.rb
    - test/pay/billable_test.rb
    - test/test_helper.rb

Documentation:
  Enabled: false

ClassAndModuleChildren:
  Enabled: false

ClassVars:
  Enabled: false

SpecialGlobalVars:
  Enabled: false

AmbiguousBlockAssociation:
  Enabled: false
